name: 'fx_crypto_provisioning'
version: '1.0.0'
config-version: 2

profile: 'fx_crypto_provisioning'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  fx_crypto_provisioning:
    bronze:
      +materialized: table
    silver:
      +materialized: table
    gold:
      +materialized: table
    dimensions:
      +materialized: table